import { window, workspace, commands, Uri } from "vscode";
import { basename, dirname } from "node:path";
import { getStrOrDefault } from "../../helpers/get-settings.func";
import { detectSrcRoot } from "../../helpers/detect-src-root.func";
import { resolveTestFilePath } from "../../helpers/resolve-test-file.func";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { hasWorkspaceOrShowError } from "../../helpers/assert-has-workspace.func";
import { EOL } from "node:os";

export async function generateTestFile(
  sourceUri: Uri,
  isForImplementLater: boolean = false,
): Promise<void> {
  if (!hasWorkspaceOrShowError()) {
    return;
  }

  const root = workspace.workspaceFolders![0].uri.fsPath;

  // Resolve config

  const cfg = workspace.getConfiguration("testFileGenerator");
  const snippetName = getStrOrDefault(cfg.get("snippetName"), () => "");
  const testRoot = getStrOrDefault(cfg.get("testRoot"), () => "test");
  const srcRoot = getStrOrDefault(cfg.get("srcRoot"), () => detectSrcRoot(root));
  const suffix = getStrOrDefault(cfg.get("testSuffix"), () => ".test");

  // Resolve path

  const testFilePath = resolveTestFilePath(
    sourceUri.fsPath,
    root,
    srcRoot,
    testRoot,
    suffix,
  );

  if (!testFilePath) {
    window.showErrorMessage(
      `TestFileGen: "${basename(sourceUri.fsPath)}" is not under ` +
        `srcRoot "${srcRoot}". workspaceRoot: "${root}"`,
    );
    return;
  }

  // Create test file

  if (!existsSync(testFilePath)) {
    try {
      mkdirSync(dirname(testFilePath), { recursive: true });
      writeFileSync(
        testFilePath,
        isForImplementLater
          ? [
              "",
              "// " +
                `TODO: Implement tests for this file ${basename(testFilePath)}`,
              "// generated by Test File Generator",
              "",
            ].join(EOL)
          : "",
        "utf-8",
      );
    } catch (error) {
      console.error("[Test File Generator] Failed to create test file:", error);
      window.showErrorMessage(
        `Test File Generator: Could not create file at "${testFilePath}".` +
          ` Check permissions.`,
      );
      return;
    }
  }

  if (isForImplementLater) {
    return;
  }

  // Open test file

  try {
    await workspace
      .openTextDocument(testFilePath)
      .then((doc) => window.showTextDocument(doc));
  } catch (error) {
    console.error("[TestFileGen] Failed to open test file:", error);
    window.showErrorMessage(`TestFileGen: Test file but could not be opened.`);
    return;
  }

  // Insert vscode snippets

  const args = snippetName.length > 0 ? { name: snippetName } : {};
  try {
    await commands.executeCommand("editor.action.insertSnippet", args);
  } catch (error) {
    console.error("[TestFileGen] Failed to insert snippet:", error);
    window.showErrorMessage(
      `TestFileGen: Failed to insert snippet: "${snippetName}"`,
    );
  }
}
